# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        django-version: [dj22, dj30, dj31]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Tox and any other packages
      run: pip install tox coveralls
      
    - name: Run coverall
      run: coveralls --service=github
      
    - name: Coveralls
      uses: coverallsapp/github-action@master
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
   # - run: |
   #     py_ver=${{ matrix.python-version }}
   #     py_ver="${py_ver/./}"
   #     test_ver="py$py_ver-dj${{ matrix.django-version }}"
   #     echo "::set-env name=test_ver::$test_ver"
   #   env:
   #     TOX_ENV: ${{ github.test_ver }}
    
    - name: Run Tox
     # Run tox using the version of Python in `PATH`
      run: tox -e "py${{ matrix.python-version }}-${{ matrix.django-version }}"
